In [2]:
import pandas as pd
import numpy as np
import os

import matplotlib.pyplot as plt

# TransPop

In [3]:
transpop = pd.read_csv('data/transpop.csv')
transpop

,Unnamed: 0,STUDYID,WEIGHT,SURVEYCOMPLETED,GRESPONDENT_DATE,GCENREG,AGE,RACE,RACE_RECODE,RACE_RECODE_CAT5,...,ACE_SEP,ACE_INC,ACE_EMO_I,ACE_PHY_I,ACE_SEX_I,ACE_IPV_I,ACE_SUB_I,ACE_MEN_I,ACE_SEP_I,ACE_INC_I
0,0,151768927,0.986143,0,26-APR-2016,1,65,6,1,1,...,0,0,1,0,0,0,0,0,0,0
1,1,152357242,0.379683,0,07-APR-2016,3,38,6,1,1,...,0,0,0,0,0,0,0,1,0,0
2,2,152444055,0.705381,0,01-MAY-2016,3,25,6,1,1,...,0,0,0,0,0,0,0,1,0,0
3,3,152525272,1.595398,0,20-APR-2016,4,18,6,1,1,...,1,1,1,0,0,1,1,1,1,1
4,4,152894493,1.870422,0,05-MAY-2016,2,30,8,3,3,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,269,194845794,0.236381,1,03-JAN-2019,4,53,1,4,5,...,0,0,0,0,0,0,1,0,0,0
270,270,194850497,0.236381,1,19-NOV-2018,4,71,6,1,1,...,0,0,0,0,1,0,1,1,0,0
271,271,194873629,0.236381,1,13-NOV-2018,1,72,6,1,1,...,0,0,1,1,0,0,0,0,0,0
272,272,195236979,2.814055,1,18-NOV-2018,1,20,6,1,1,...,0,0,1,0,1,0,0,1,0,0
273,273,196860170,2.354026,1,30-NOV-2018,2,34,6,1,1,...,1,0,1,0,0,0,0,0,1,0

In [4]:
transpop.columns

Index(['Unnamed: 0', 'STUDYID', 'WEIGHT', 'SURVEYCOMPLETED',
       'GRESPONDENT_DATE', 'GCENREG', 'AGE', 'RACE', 'RACE_RECODE',
       'RACE_RECODE_CAT5',
       ...
       'ACE_SEP', 'ACE_INC', 'ACE_EMO_I', 'ACE_PHY_I', 'ACE_SEX_I',
       'ACE_IPV_I', 'ACE_SUB_I', 'ACE_MEN_I', 'ACE_SEP_I', 'ACE_INC_I'],
      dtype='object', length=567)

In [5]:
transpop.describe()

,Unnamed: 0,STUDYID,WEIGHT,SURVEYCOMPLETED,AGE,RACE,RACE_RECODE,RACE_RECODE_CAT5,SEX,GENDER,...,NEGEXPFUTURE_I,ACE_I,ACE_EMO_I,ACE_PHY_I,ACE_SEX_I,ACE_IPV_I,ACE_SUB_I,ACE_MEN_I,ACE_SEP_I,ACE_INC_I
count,274.000000,2.740000e+02,274.000000,274.000000,274.000000,274.000000,274.000000,274.000000,274.000000,274.000000,...,274.000000,274.000000,274.000000,274.000000,274.000000,274.000000,274.000000,274.000000,274.000000,274.000000
mean,136.500000,1.718596e+08,1.000000,0.813869,39.361314,5.762774,1.937956,1.762774,1.525547,3.299270,...,3.176805,3.208029,0.704380,0.430657,0.401460,0.288321,0.394161,0.496350,0.357664,0.135036
std,79.241193,1.057721e+07,0.864983,0.389925,16.889344,1.689854,1.672822,1.266040,0.500261,1.436647,...,0.915362,2.094072,0.457156,0.496074,0.491091,0.453810,0.489564,0.500902,0.480190,0.342388
min,0.000000,1.517689e+08,0.236381,0.000000,18.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,68.250000,1.681479e+08,0.317048,1.000000,24.000000,6.000000,1.000000,1.000000,1.000000,2.000000,...,2.666667,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,136.500000,1.726608e+08,0.645186,1.000000,34.000000,6.000000,1.000000,1.000000,2.000000,4.000000,...,3.222222,3.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,204.750000,1.765349e+08,1.373568,1.000000,54.000000,6.000000,2.000000,2.000000,2.000000,5.000000,...,3.861111,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
max,273.000000,1.968602e+08,2.814055,1.000000,72.000000,9.000000,7.000000,5.000000,2.000000,5.000000,...,5.000000,8.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [6]:
cisgender = pd.read_csv('data/cisgender.csv')
cisgender

,Unnamed: 0,STUDYID,WEIGHT,GMETHOD_TYPE,GRESPONDENT_DATE,GCENREG,AGE,RACE,RACE_RECODE,RACE_RECODE_CAT5,...,ACE_SUB,ACE_SUB_I,ACE_MEN,ACE_MEN_I,ACE_SEP,ACE_SEP_I,ACE_INC,ACE_INC_I,LIFESAT,LIFESAT_I
0,0,196226208,0.255088,SCAN,28-DEC-2018,2,68,6,1,1,...,1,1,0,0,0,0,0,0,4.1999998092651,4.2
1,1,175270682,0.723258,SCAN,20-MAR-2018,2,67,6,1,1,...,1,1,0,0,1,1,0,0,2,2.0
2,2,175300494,2.187140,WEB,22-FEB-2018,2,47,6,1,1,...,1,1,1,1,1,1,0,0,6.5999999046326,6.6
3,3,196175230,0.877834,WEB,29-NOV-2018,4,38,6,1,1,...,0,0,0,0,0,0,0,0,5.5999999046326,5.6
4,4,175300700,0.948836,WEB,15-MAR-2018,4,25,6,1,1,...,1,1,1,1,1,1,0,0,5.1999998092651,5.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1157,1157,195669344,1.738075,WEB,29-NOV-2018,2,20,6,1,1,...,0,0,0,0,0,0,0,0,6,6.0
1158,1158,195896207,0.371366,SCAN,27-DEC-2018,4,56,5,5,5,...,0,0,1,1,1,1,0,0,2.5999999046326,2.6
1159,1159,175276145,0.797851,WEB,02-MAR-2018,4,47,6,1,1,...,0,0,0,0,1,1,0,0,6.4000000953674,6.4
1160,1160,175291515,1.780040,WEB,22-FEB-2018,3,26,6,1,1,...,0,0,1,1,0,0,0,0,5.4000000953674,5.4
1161,1161,196221469,0.750153,WEB,03-DEC-2018,1,57,2,2,2,...,0,0,0,0,0,0,0,0,4.5999999046326,4.6

In [7]:
combined = pd.read_csv('data/combined.csv')
combined

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/IPython/core/interactiveshell.py:3251: DtypeWarning: Columns (8,18,19,20,22,23,25,39,74,75,77,215,297,298,306,307,308,309,311,312,313) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Unnamed: 0,STUDYID,WEIGHT_CISGENDER_TRANSPOP,WEIGHT_CISGENDER,WEIGHT_TRANSPOP,GMETHOD_TYPE,SURVEYCOMPLETED,GRESPONDENT_DATE,GCENREG,RACE,...,ACE_SEP,ACE_INC,ACE_EMO_I,ACE_PHY_I,ACE_SEX_I,ACE_IPV_I,ACE_SUB_I,ACE_MEN_I,ACE_SEP_I,ACE_INC_I
0,0,151768927,0.022039,,.9861429333687,,0,26-APR-2016,1,6,...,0,0,1,0,0,0,0,0,0,0
1,1,152357242,0.008485,,.3796825110912,,0,07-APR-2016,3,6,...,0,0,0,0,0,0,0,1,0,0
2,2,152444055,0.015764,,.705381155014,,0,01-MAY-2016,3,6,...,0,0,0,0,0,0,0,1,0,0
3,3,152525272,0.035655,,1.5953975915909,,0,20-APR-2016,4,6,...,1,1,1,0,0,1,1,1,1,1
4,4,152894493,0.041802,,1.870422244072,,0,05-MAY-2016,2,8,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1431,1431,197167223,6.299798,5.1374626159668,,SCAN,2,27-DEC-2018,4,3,...,0,0,1,1,0,1,1,1,0,0
1432,1432,197167224,0.581383,.4741154909134,,SCAN,2,15-JAN-2019,4,6,...,0,0,1,0,1,0,0,1,0,0
1433,1433,197168195,2.584832,2.1079211235046,,WEB,2,13-DEC-2018,1,6,...,0,0,1,1,1,1,0,1,0,0
1434,1434,197169207,0.545099,.4445266127586,,WEB,2,08-DEC-2018,4,6,...,0,0,0,0,0,0,0,0,0,0
1435,1435,197169232,1.580057,1.2885310649872,,SCAN,2,04-JAN-2019,1,2,...,0,0,1,0,1,1,1,0,0,0

**Counseling/therapy (Q69-Q73, p.6)**
- Q69: Have you ever had any counseling/therapy? 1: Yes, 2: No
- Q70: At what age did you begin counseling/therapy?
- T2Q71: Have you ever had counseling/therapy to discuss your gender identity or transgener identity with a professional? 1: Yes, 2: No
- T2Q72: At what age did you begin counseling/therapy to discuss your gender identity or transgender identity?
- Q73_1 & Q73_2: From whom did you receive treatment?

**Health insurance**: Q81_1-13

**Health care utilization**: Q82-83

**Health care satisfaction**: Q84

**Healthcare access**
- Q85: Do you have one person you think of as your personal doctor or healthcare provider? Yes or No
- T2Q86: What type of personal doctor or health provider is this person?
- Q88: Was there a time in the past 12 months when you needed to see a doctor but could not because of cost? Yes or No

**Physical Health Outcome**: Q97 - Have you EVER been told by a doctor or health professional that you had any of the following? Please mark all that apply.

**Disability**: 
- Q98: Are you limited in any way in any activities because of physical, mental, or emotional problems? Yes or No
- Q99: Do you now have any health problem that requires you to use specia equipment, such as a care, a wheelchair, a special bed.  Yes or NO

**HIV/STI**
- Q105: About how often do you get tested for sexually transmitted infections (STIs) other than HIV? 
- Q106: About how often do you get tested for HIV?

In [8]:
combined[['Q69', 'Q70', 'Q71', 'Q72', 'Q73_1','Q73_2', 'Q81_1', 'Q81_2','Q81_3','Q81_4','Q81_5','Q81_6','Q81_7','Q81_8', 'Q81_9','Q81_10','Q81_11',
 'Q81_12','Q81_13', 'Q84', 'Q85', 'Q86', 'Q87']]

,Q69,Q70,Q71,Q72,Q73_1,Q73_2,Q81_1,Q81_2,Q81_3,Q81_4,...,Q81_8,Q81_9,Q81_10,Q81_11,Q81_12,Q81_13,Q84,Q85,Q86,Q87
0,2,97,7,97,7,7,,2,,,...,8,,,,,,7,1,,
1,1,27,,97,,,,,,,...,,,,,,,7,1,,
2,1,22,,97,,,,,,,...,,,,11,,,7,1,,
3,1,,,97,,,,,,4,...,,,,,,,7,2,97,
4,1,27,,97,,,,,,,...,,,,11,,,7,1,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1431,1,16,,,1,,,,,4,...,,,,,,,1,1,1,
1432,1,69,,,1,,,,,,...,8,,,,,,4,1,1,
1433,1,25,,,1,,,,,,...,,9,,,,,7,1,1,
1434,2,97,,,7,7,,,,,...,,,,,,,2,2,97,
1435,1,34,,,,2,,,,,...,8,9,,11,,,2,1,1,

#### Income
- Two income variable: household income (variable hinc) and personal income (variable: pinc))
- The responses from TransPop 1 (t1q198 and t1q200, respectively) and TransPop 2 (t2q204 and t2q206, respectively) were collapsed
- The responses from Cisgender were constructed from q155 and q157, respectively. 
 - 95 respondents did not indicate a household income on the survey.

In [9]:
reference = { 'TransPop 1': ['Under $720', '$720 to $5,999', '$6,000 to $11,999',
                             '$12,000 to $23,999', '$24,000 to $35,999',
                             '$36,000 to $47,999', '$48,000 to $59,999',
                             '$60,000 to $89,999', '$90,000 to $119,999',
                             '$120,000 to $179,999', '$180,000 to $239,999', '$240,000 and over'],
             'TransPop 2': ['No income', '$1 to $4,999', '$5,000 to $9,999',
                            '$10,000 to $14,999', '$15,000 to $19,999',
                            '$20,000 to $24,999', '$25,000 to $29,999','$30,000 to $39,999',
                            '$40,000 to $49,999', '$50,000 to $59,999', '$60,000 to $74,999',
                            '$75,000 to $99,999', '$100,000 to $149,999', '$150,000 or more']}

Question: Are transgender people facing higher possibilities to encounter harassment and violence
Columns:
1. Everyday discrimination:(TransPop: q171a-q171i,Cisgender: q121a-q121i). The resulting variable was reverse-coded so that lower values represent less everyday discrimination and higher values represent more everyday discrimination. Scale value range from 1 to 4. 
  - **“everyday”** (calculated only from complete cases, in which no individual scale items were missing) and **“everyday_i”** (missing individual scale items were imputed, and a final scale score was calculated for each respondent).
2. Community connectedness (TransPop only): q51-q55
  - Lower scores represented lower community connectedness, while higher scores represented greater community connectedness. Scale values range from 1 to 5. 
  - “connectedness” (calculated only from complete cases, in which no individual scale items were missing) and “connectedness_i” (missing individual scale items were imputed, and a final scale score was calculated for each respondent). 
3.

1. Healthcare Stereotype Threat (TransPop only): q77-q80
  - “hcthreat” (calculated only from complete cases, in which no individual scale items were missing) and “hcthreat_i” (missing individual scale items were imputed, and a final scale score was calculated for each respondent). 
2.

*Violence and Discrimination* (whether transgenders are more likely to encounter violence than cisgenders) Bullying (Q189, 190, p.15) Victimization and Discrimination (Q162- Q168, p.12) Household intimate partner violence: (TransPop: Q183) Adverse Childhood Experiences (Q178-Q188) ace, ace_emo, ace_phy, ace_sex, ace_ipv, ace_men Everyday discrimination (TransPop: Q171.a - ii and Cisgender: Q121.a - i, p.14)

In [10]:
trans_column = transpop.columns.tolist()
trans_column

['Unnamed: 0',
 'STUDYID',
 'WEIGHT',
 'SURVEYCOMPLETED',
 'GRESPONDENT_DATE',
 'GCENREG',
 'AGE',
 'RACE',
 'RACE_RECODE',
 'RACE_RECODE_CAT5',
 'SEXUALID',
 'SEXMINID',
 'SEX',
 'GENDER',
 'HINC',
 'HINC_I',
 'PINC',
 'PINC_I',
 'GEDUC1',
 'GEDUC2',
 'GURBAN',
 'GURBAN_I',
 'POVERTY',
 'POVERTY_I',
 'POVERTYCAT',
 'POVERTYCAT_I',
 'GANN_INC',
 'GANN_INC2',
 'GD74',
 'GD75',
 'GD76',
 'GEDUCATION',
 'GEMPLOYMENT2010',
 'GMSANAME',
 'GRACE',
 'GZIPCODE',
 'GZIPSTATE',
 'GD7',
 'GRUCA',
 'GRUCA_I',
 'GMILESAWAY',
 'GCENDIV',
 'Q01',
 'Q02',
 'Q03',
 'Q04',
 'Q05',
 'Q06',
 'Q07',
 'Q08',
 'Q09',
 'Q10',
 'Q11',
 'Q12',
 'Q13',
 'Q14',
 'Q15',
 'Q16',
 'Q17',
 'Q18',
 'Q19A',
 'Q19B',
 'Q19C',
 'Q19D',
 'Q20_1',
 'Q20_2',
 'Q20_3',
 'Q20_4',
 'Q20_5',
 'Q20_6',
 'Q20_7',
 'Q21_VERB',
 'Q22',
 'Q23',
 'Q24',
 'Q25',
 'Q26',
 'Q27',
 'T2Q28',
 'T2Q29',
 'T2Q30',
 'Q31',
 'Q32',
 'Q33',
 'Q34',
 'Q34_VERB',
 'Q35_1',
 'Q35_2',
 'Q35_3',
 'Q35_4',
 'Q35_5',
 'Q36A',
 'Q36B',
 'Q36C',
 'Q36D',
 'Q36E',
 'Q36F',
 'Q37',
 'Q38',
 'Q39',
 'Q40',
 'Q41',
 'Q42',
 'Q43',
 'Q44',
 'Q45',
 'Q46',
 'Q47',
 'Q48',
 'Q49',
 'Q50',
 'Q51',
 'Q52',
 'Q53',
 'Q54',
 'Q55',
 'Q56',
 'Q57',
 'Q58',
 'Q59',
 'Q60',
 'Q61',
 'Q62A',
 'Q62B',
 'Q62C',
 'Q62D',
 'Q62E',
 'Q62_T_VERB',
 'Q63A',
 'Q63B',
 'Q63C',
 'Q63D',
 'Q63E',
 'Q63F',
 'Q63G',
 'Q63H',
 'Q63I',
 'Q63J',
 'Q63_T_VERB',
 'Q64',
 'Q65',
 'Q66',
 'Q67',
 'Q68',
 'Q69',
 'Q70',
 'T2Q71',
 'T2Q72',
 'Q73_1',
 'Q73_2',
 'Q74',
 'Q75',
 'Q76_1',
 'Q76_2',
 'Q77',
 'Q78',
 'Q79',
 'Q80',
 'Q81_1',
 'Q81_2',
 'Q81_3',
 'Q81_4',
 'Q81_5',
 'Q81_6',
 'Q81_7',
 'Q81_8',
 'Q81_9',
 'Q81_10',
 'Q81_11',
 'Q81_12',
 'Q81_13',
 'Q81_T_VERB',
 'Q82',
 'Q83_1',
 'Q83_2',
 'Q83_3',
 'Q83_4',
 'Q83_5',
 'Q83_T_VERB',
 'Q84',
 'Q85',
 'Q86_VERB',
 'T2Q86',
 'T2Q87',
 'Q88',
 'Q89',
 'Q90_1',
 'Q90_2',
 'Q90_3',
 'Q91',
 'Q92A',
 'Q92B',
 'Q92C',
 'Q92D',
 'Q93',
 'Q94',
 'Q95',
 'Q96',
 'Q97_1',
 'Q97_2',
 'Q97_3',
 'Q97_4',
 'Q97_5',
 'Q97_6',
 'Q97_7',
 'Q97_8',
 'Q97_9',
 'Q97_10',
 'Q97_11',
 'Q97_12',
 'Q97_13',
 'Q97_14',
 'Q97_15',
 'Q97_16',
 'Q97_17',
 'Q97_18',
 'Q97_19',
 'Q97_20',
 'Q97_21',
 'Q97_22',
 'Q97_23',
 'Q98',
 'Q99',
 'Q100A',
 'Q100B',
 'Q100C',
 'Q100D',
 'Q100E',
 'Q100F',
 'Q101',
 'Q102',
 'Q103',
 'Q104',
 'Q105',
 'Q106',
 'Q107',
 'Q108',
 'Q109',
 'Q110',
 'Q111',
 'Q112',
 'Q113',
 'Q114',
 'Q115',
 'Q116',
 'Q117',
 'Q118',
 'Q119',
 'Q120',
 'Q121',
 'Q122',
 'Q123',
 'Q124',
 'Q125',
 'Q126',
 'Q127',
 'Q128',
 'Q129',
 'Q130',
 'Q131',
 'Q132',
 'Q133',
 'Q134',
 'Q135',
 'Q136',
 'Q137',
 'Q138',
 'Q139',
 'Q140',
 'Q141',
 'Q142',
 'Q143',
 'Q144',
 'Q145',
 'Q146',
 'Q147',
 'Q148',
 'Q149',
 'Q150A',
 'Q150B',
 'Q150C',
 'Q150D',
 'Q150E',
 'Q150F',
 'Q151',
 'Q152',
 'Q153',
 'Q154',
 'Q155',
 'Q156',
 'Q157',
 'Q158',
 'Q159',
 'Q160',
 'Q161',
 'Q162A',
 'Q162B',
 'Q162C',
 'Q162D',
 'Q162E',
 'Q162F',
 'Q163_1',
 'Q163_2',
 'Q163_3',
 'Q163_4',
 'Q163_5',
 'Q163_6',
 'Q163_7',
 'Q163_8',
 'Q163_9',
 'Q163_10',
 'Q164',
 'Q165',
 'Q166_1',
 'Q166_2',
 'Q166_3',
 'Q166_4',
 'Q166_5',
 'Q166_6',
 'Q166_7',
 'Q166_8',
 'Q166_9',
 'Q166_10',
 'Q167',
 'Q168_1',
 'Q168_2',
 'Q168_3',
 'Q168_4',
 'Q168_5',
 'Q168_6',
 'Q168_7',
 'Q168_8',
 'Q168_9',
 'Q168_10',
 'Q169A',
 'Q169B',
 'Q169C',
 'Q169D',
 'Q169E',
 'Q169F',
 'Q169G',
 'Q169H',
 'Q169I',
 'Q169J',
 'Q169K',
 'Q170_1',
 'Q170_2',
 'Q170_3',
 'Q170_4',
 'Q170_5',
 'Q170_6',
 'Q170_7',
 'Q170_8',
 'Q170_9',
 'Q170_10',
 'Q171A',
 'Q171B',
 'Q171C',
 'Q171D',
 'Q171E',
 'Q171F',
 'Q171G',
 'Q171H',
 'Q171I',
 'Q172_1',
 'Q172_2',
 'Q172_3',
 'Q172_4',
 'Q172_5',
 'Q172_6',
 'Q172_7',
 'Q172_8',
 'Q172_9',
 'Q172_10',
 'Q173A',
 'Q173B',
 'Q173C',
 'Q173D',
 'Q173E',
 'Q173F',
 'Q173G',
 'Q173H',
 'Q173I',
 'Q173J',
 'Q173K',
 'Q173L',
 'Q174',
 'Q175',
 'Q176',
 'Q177',
 'Q178',
 'Q179',
 'Q180',
 'Q181',
 'Q182',
 'Q183',
 'Q184',
 'Q185',
 'Q186',
 'Q187',
 'Q188',
 'Q189',
 'Q190_1',
 'Q190_2',
 'Q190_3',
 'Q190_4',
 'Q190_5',
 'Q190_6',
 'Q190_7',
 'Q190_8',
 'Q190_9',
 'Q190_10',
 'Q191A',
 'Q191B',
 'Q191C',
 'Q191D',
 'Q191E',
 'Q191F',
 'Q191G',
 'Q191H',
 'Q191I',
 'Q192A',
 'Q192B',
 'Q192C',
 'Q192D',
 'Q192E',
 'Q192F',
 'Q192G',
 'Q192H',
 'Q192I',
 'Q192J',
 'Q192K',
 'Q192L',
 'Q193_1',
 'Q193_2',
 'Q193_3',
 'Q193_4',
 'Q193_5',
 'Q193_6',
 'Q193_T_VERB',
 'Q194',
 'Q195',
 'Q196',
 'Q197',
 'Q198',
 'Q199',
 'Q200',
 'Q201_1',
 'Q201_2',
 'Q201_3',
 'Q201_4',
 'Q202_1',
 'Q202_2',
 'Q202_3',
 'Q202_4',
 'Q202_5',
 'Q202_6',
 'Q202_7',
 'Q202_8',
 'Q202_9',
 'Q202_10',
 'Q202_VERB',
 'T2Q203_1',
 'T2Q203_2',
 'T2Q203_3',
 'T2Q204',
 'Q205',
 'Q205_I',
 'T2Q206',
 'Q207',
 'Q208',
 'Q209_1',
 'Q209_2',
 'Q209_3',
 'Q209_4',
 'Q209_5',
 'Q209_6',
 'Q209_7',
 'Q209_8',
 'Q209_9',
 'Q209_10',
 'Q209_11',
 'Q209_12',
 'Q210',
 'Q211',
 'Q212',
 'Q213',
 'Q214',
 'Q215',
 'Q216',
 'Q217',
 'Q218',
 'Q219_1',
 'Q219_2',
 'Q219_3',
 'Q219_4',
 'Q219_5',
 'Q220',
 'Q221_1',
 'Q221_2',
 'Q221_3',
 'Q222',
 'Q223',
 'Q224',
 'Q225',
 'Q226',
 'Q227',
 'Q228',
 'T1Q27',
 'T1Q28',
 'T1Q198',
 'T1Q200',
 'TRANS',
 'SOCIALWB',
 'SOCIALWB_I',
 'MEIM',
 'MEIM_I',
 'KESSLER6',
 'KESSLER6_I',
 'AUDITC',
 'AUDITC_I',
 'DUDIT',
 'DUDIT_I',
 'EVERYDAY',
 'EVERYDAY_I',
 'CHILDGNC',
 'CHILDGNC_I',
 'SOCSUPPORT',
 'SOCSUPPORT_I',
 'SOCSUPPORT_SO',
 'SOCSUPPORT_SO_I',
 'SOCSUPPORT_FAM',
 'SOCSUPPORT_FAM_I',
 'SOCSUPPORT_FR',
 'SOCSUPPORT_FR_I',
 'LIFESAT',
 'LIFESAT_I',
 'CONNECTEDNESS',
 'CONNECTEDNESS_I',
 'HCTHREAT',
 'HCTHREAT_I',
 'INTERNALIZED',
 'INTERNALIZED_I',
 'NONDISCLOSURE',
 'NONDISCLOSURE_I',
 'NONAFFIRM',
 'NONAFFIRM_I',
 'NEGEXPFUTURE',
 'NEGEXPFUTURE_I',
 'ACE',
 'ACE_I',
 'ACE_EMO',
 'ACE_PHY',
 'ACE_SEX',
 'ACE_IPV',
 'ACE_SUB',
 'ACE_MEN',
 'ACE_SEP',
 'ACE_INC',
 'ACE_EMO_I',
 'ACE_PHY_I',
 'ACE_SEX_I',
 'ACE_IPV_I',
 'ACE_SUB_I',
 'ACE_MEN_I',
 'ACE_SEP_I',
 'ACE_INC_I']

In [11]:
trans_violent_col = ['Q162A','Q162B','Q162C','Q162D','Q162E','Q162F','Q163_1','Q163_2','Q163_3','Q163_4','Q163_5',
              'Q163_6','Q163_7','Q163_8','Q163_9','Q163_10','Q164','Q165','Q166_1','Q166_2','Q166_3','Q166_4','Q166_5',
               'Q166_6','Q166_7','Q166_8','Q166_9','Q166_10','Q167','Q168_1','Q168_2','Q168_3','Q168_4','Q168_5','Q168_6',
               'Q168_7','Q168_8','Q168_9','Q168_10'
              ]
trans_house_violent_col = ['Q183']
trans_childhood_col = ['Q121']

In [12]:
violence_df = transpop[trans_violent_col]
violence_df

,Q162A,Q162B,Q162C,Q162D,Q162E,Q162F,Q163_1,Q163_2,Q163_3,Q163_4,...,Q168_1,Q168_2,Q168_3,Q168_4,Q168_5,Q168_6,Q168_7,Q168_8,Q168_9,Q168_10
0,1,3,2,2,2,1,,,,,...,7,7,7,7,7,7,97,97,97,97
1,1,3,2,2,4,4,,,,4,...,7,7,7,7,7,7,97,97,97,97
2,4,1,1,3,4,4,,2,3,4,...,7,7,7,7,7,7,97,97,97,97
3,1,1,1,1,1,1,7,7,7,7,...,7,7,7,7,7,7,97,97,97,97
4,1,2,1,2,3,1,1,2,,,...,7,7,7,7,7,7,97,97,97,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,4,4,4,4,4,4,,2,3,,...,7,7,7,7,7,7,97,97,97,97
270,2,2,2,1,1,1,,,,,...,7,7,7,7,7,7,97,97,97,97
271,1,2,1,1,4,1,,,,,...,7,7,7,7,7,7,97,97,97,97
272,1,1,1,1,4,1,,2,,4,...,7,7,7,7,7,7,97,97,97,97
273,3,2,1,3,4,3,,,3,4,...,,,,,,6,,,,

In [13]:
cis_cols = cisgender.columns.tolist()
cis_cols
#cisgender has different survey

['Unnamed: 0',
 'STUDYID',
 'WEIGHT',
 'GMETHOD_TYPE',
 'GRESPONDENT_DATE',
 'GCENREG',
 'AGE',
 'RACE',
 'RACE_RECODE',
 'RACE_RECODE_CAT5',
 'SEXUALID',
 'SEXMINID',
 'SEX',
 'GENDER',
 'HINC',
 'HINC_I',
 'PINC',
 'PINC_I',
 'GEDUC1',
 'GEDUC2',
 'GRACE_I',
 'GRUCA_I',
 'GURBAN',
 'GURBAN_I',
 'POVERTY',
 'POVERTY_I',
 'POVERTYCAT',
 'POVERTYCAT_I',
 'GD25A',
 'GD65',
 'GD66',
 'GD66A',
 'GP20',
 'GANN_INC',
 'GANN_INC2',
 'GD1',
 'GD15C',
 'GD4_1',
 'GD5',
 'GD63',
 'GD69',
 'GD69_1',
 'GD69_2',
 'GD69_3',
 'GD69_4',
 'GD69_5',
 'GD74',
 'GD75',
 'GD76',
 'GD8B',
 'GD9',
 'GEDUCATION',
 'GEMPLOYMENT2010',
 'GMSANAME',
 'GP1',
 'GP2',
 'GRACE',
 'GSURVEY',
 'GWP10200',
 'GWP10202',
 'GWP10208',
 'GWP10209',
 'GWP10215',
 'GWP10216',
 'GWP119',
 'GWP1223',
 'GWP1225',
 'GZIPCODE',
 'GZIPSTATE',
 'GRUCA',
 'GMILESAWAY',
 'GCENDIV',
 'Q01',
 'Q02',
 'Q03',
 'Q04',
 'Q05',
 'Q06',
 'Q07',
 'Q08',
 'Q09',
 'Q10',
 'Q11',
 'Q12',
 'Q13',
 'Q14',
 'Q15',
 'Q16',
 'Q17',
 'Q18',
 'Q19A',
 'Q19B',
 'Q19C',
 'Q19D',
 'Q20_1',
 'Q20_2',
 'Q20_3',
 'Q20_4',
 'Q20_5',
 'Q20_6',
 'Q20_7',
 'Q21',
 'Q21_VERB',
 'Q22',
 'Q23',
 'Q24',
 'Q25',
 'Q26',
 'Q27',
 'Q28',
 'Q29',
 'Q30',
 'Q31',
 'Q32',
 'Q32_VERB',
 'Q33_1',
 'Q33_2',
 'Q33_3',
 'Q33_4',
 'Q33_5',
 'Q34A',
 'Q34B',
 'Q34C',
 'Q34D',
 'Q34E',
 'Q34F',
 'Q35',
 'Q36',
 'Q37',
 'Q38',
 'Q39',
 'Q40',
 'Q41',
 'Q42',
 'Q43',
 'Q44_1',
 'Q44_2',
 'Q45_1',
 'Q45_2',
 'Q45_3',
 'Q45_4',
 'Q45_5',
 'Q45_6',
 'Q45_7',
 'Q45_8',
 'Q45_9',
 'Q45_10',
 'Q45_11',
 'Q45_12',
 'Q45_13',
 'Q45_VERB',
 'Q46',
 'Q47_1',
 'Q47_2',
 'Q47_3',
 'Q47_4',
 'Q47_5',
 'Q47_VERB',
 'Q48',
 'Q49',
 'Q50',
 'Q50_VERB',
 'Q51',
 'Q52',
 'Q53A',
 'Q53B',
 'Q53C',
 'Q53D',
 'Q54',
 'Q55',
 'Q56',
 'Q57',
 'Q58_1',
 'Q58_2',
 'Q58_3',
 'Q58_4',
 'Q58_5',
 'Q58_6',
 'Q58_7',
 'Q58_8',
 'Q58_9',
 'Q58_10',
 'Q58_11',
 'Q58_12',
 'Q58_13',
 'Q58_14',
 'Q58_15',
 'Q58_16',
 'Q58_17',
 'Q58_18',
 'Q58_19',
 'Q58_20',
 'Q58_21',
 'Q58_22',
 'Q58_23',
 'Q59',
 'Q60',
 'Q61A',
 'Q61B',
 'Q61C',
 'Q61D',
 'Q61E',
 'Q61F',
 'Q62',
 'Q63',
 'Q64',
 'Q65',
 'Q66',
 'Q67',
 'Q68',
 'Q69',
 'Q70',
 'Q71',
 'Q72',
 'Q73',
 'Q74',
 'Q75',
 'Q76',
 'Q77',
 'Q78',
 'Q79',
 'Q80',
 'Q81',
 'Q82',
 'Q83',
 'Q84',
 'Q85',
 'Q86',
 'Q87',
 'Q88',
 'Q89',
 'Q90',
 'Q91',
 'Q92',
 'Q93',
 'Q94',
 'Q95',
 'Q96',
 'Q97',
 'Q98',
 'Q99',
 'Q100',
 'Q101',
 'Q102',
 'Q103',
 'Q104',
 'Q105',
 'Q106',
 'Q107',
 'Q108',
 'Q109',
 'Q110',
 'Q111A',
 'Q111B',
 'Q111C',
 'Q111D',
 'Q111E',
 'Q111F',
 'Q112A',
 'Q112B',
 'Q112C',
 'Q112D',
 'Q112E',
 'Q112F',
 'Q113_1',
 'Q113_2',
 'Q113_3',
 'Q113_4',
 'Q113_5',
 'Q113_6',
 'Q113_7',
 'Q113_8',
 'Q113_9',
 'Q113_10',
 'Q114',
 'Q115',
 'Q116_1',
 'Q116_2',
 'Q116_3',
 'Q116_4',
 'Q116_5',
 'Q116_6',
 'Q116_7',
 'Q116_8',
 'Q116_9',
 'Q116_10',
 'Q117',
 'Q118_1',
 'Q118_2',
 'Q118_3',
 'Q118_4',
 'Q118_5',
 'Q118_6',
 'Q118_7',
 'Q118_8',
 'Q118_9',
 'Q118_10',
 'Q119A',
 'Q119B',
 'Q119C',
 'Q119D',
 'Q119E',
 'Q119F',
 'Q119G',
 'Q119H',
 'Q119I',
 'Q119J',
 'Q119K',
 'Q120_1',
 'Q120_2',
 'Q120_3',
 'Q120_4',
 'Q120_5',
 'Q120_6',
 'Q120_7',
 'Q120_8',
 'Q120_9',
 'Q120_10',
 'Q121A',
 'Q121B',
 'Q121C',
 'Q121D',
 'Q121E',
 'Q121F',
 'Q121G',
 'Q121H',
 'Q121I',
 'Q122_1',
 'Q122_2',
 'Q122_3',
 'Q122_4',
 'Q122_5',
 'Q122_6',
 'Q122_7',
 'Q122_8',
 'Q122_9',
 'Q122_10',
 'Q123A',
 'Q123B',
 'Q123C',
 'Q123D',
 'Q123E',
 'Q123F',
 'Q123G',
 'Q123H',
 'Q123I',
 'Q123J',
 'Q123K',
 'Q123L',
 'Q124',
 'Q125',
 'Q126',
 'Q127',
 'Q128',
 'Q129',
 'Q130',
 'Q131',
 'Q132',
 'Q133',
 'Q134',
 'Q135',
 'Q136',
 'Q137',
 'Q138',
 'Q139',
 'Q140_1',
 'Q140_2',
 'Q140_3',
 'Q140_4',
 'Q140_5',
 'Q140_6',
 'Q140_7',
 'Q140_8',
 'Q140_9',
 'Q140_10',
 'Q141A',
 'Q141B',
 'Q141C',
 'Q141D',
 'Q141E',
 'Q141F',
 'Q141G',
 'Q141H',
 'Q141I',
 'Q141J',
 'Q141K',
 'Q141L',
 'Q142',
 'Q143_1',
 'Q143_2',
 'Q143_3',
 'Q143_4',
 'Q143_5',
 'Q143_6',
 'Q143_7',
 'Q144',
 'Q145',
 'Q146',
 'Q147',
 'Q148',
 'Q149',
 'Q150',
 'Q151',
 'Q152_1',
 'Q152_2',
 'Q152_3',
 'Q152_4',
 'Q153_1',
 'Q153_2',
 'Q153_3',
 'Q153_4',
 'Q153_5',
 'Q153_6',
 'Q153_7',
 'Q153_8',
 'Q153_9',
 'Q153_10',
 'Q153_VERB',
 'Q154_1',
 'Q154_2',
 'Q154_3',
 'Q155',
 'Q156',
 'Q156_I',
 'Q157',
 'Q158',
 'Q159',
 'Q160_1',
 'Q160_2',
 'Q160_3',
 'Q160_4',
 'Q160_5',
 'Q160_6',
 'Q160_7',
 'Q160_8',
 'Q160_9',
 'Q160_10',
 'Q160_11',
 'Q160_12',
 'Q161',
 'Q162',
 'Q163',
 'Q164',
 'Q165',
 'Q166',
 'Q167',
 'Q168_1',
 'Q168_2',
 'Q168_3',
 'Q168_4',
 'Q168_5',
 'Q169',
 'Q170_1',
 'Q170_2',
 'Q170_3',
 'Q171',
 'Q172',
 'Q173',
 'Q174',
 'Q175',
 'Q176',
 'Q177',
 'SOCIALWB',
 'SOCIALWB_I',
 'MEIM',
 'MEIM_I',
 'KESSLER6',
 'KESSLER6_I',
 'AUDITC',
 'AUDITC_I',
 'DUDIT',
 'DUDIT_I',
 'EVERYDAY',
 'EVERYDAY_I',
 'CHILDGNC',
 'CHILDGNC_I',
 'SOCSUPPORT',
 'SOCSUPPORT_I',
 'SOCSUPPORT_SO',
 'SOCSUPPORT_SO_I',
 'SOCSUPPORT_FAM',
 'SOCSUPPORT_FAM_I',
 'SOCSUPPORT_FR',
 'SOCSUPPORT_FR_I',
 'ACE',
 'ACE_I',
 'ACE_EMO',
 'ACE_EMO_I',
 'ACE_PHY',
 'ACE_PHY_I',
 'ACE_SEX',
 'ACE_SEX_I',
 'ACE_IPV',
 'ACE_IPV_I',
 'ACE_SUB',
 'ACE_SUB_I',
 'ACE_MEN',
 'ACE_MEN_I',
 'ACE_SEP',
 'ACE_SEP_I',
 'ACE_INC',
 'ACE_INC_I',
 'LIFESAT',
 'LIFESAT_I']